# Source:
# https://github.com/arduino/tooling-project-assets/blob/main/issue-templates/template-choosers/general/config.yml
blank_issues_enabled: false
contact_links:
  - name: Reference manual
    url: https://rei-vilo.github.io/PDLS_EXT3_Basic_Documentation/html/index.html
    about: The Reference manual lists all the objects and functions, with details for their parameters and returned results.
  - name: User guide
    url: https://pdls.pervasivedisplays.com/userguide/index.html
    about: The User guide focuses on how to use the different libraries, with commented examples
