name: Check Internationalization

env:
  # See vars.GO_VERSION field of https://github.com/arduino/arduino-cli/blob/master/DistTasks.yml
  GO_VERSION: "1.19"

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - '.github/workflows/check-i18n-task.ya?ml'
      - '**/package.json'
      - '**.ts'
      - 'i18n/**'
  pull_request:
    paths:
      - '.github/workflows/check-i18n-task.ya?ml'
      - '**/package.json'
      - '**.ts'
      - 'i18n/**'
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js 16.14
        uses: actions/setup-node@v3
        with:
          node-version: '16.14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Install dependencies
        run: yarn
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for errors
        run: yarn i18n:check
